name: Publish NPM Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: publish
        run: npm publish --access public
        working-directory: p2d
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
